# Generated by Django 4.1.7 on 2023-03-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SensorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="uts_app.sensor",
                    ),
                ),
            ],
        ),
    ]
